version: '3.8'
services:
  web:
    build: .
    container_name: gaia_external_brain
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
  db:
    image: postgres:15
    container_name: gaia_external_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gaia
      POSTGRES_PASSWORD: gaia
      POSTGRES_DB: gaia_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: gaia_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  pgdata:
